POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0Mzk1OTU4YWQzOTNiMjE4ZDhhZGM2YSIsImlhdCI6MTY4MTQ4MDA2MH0.jd5fkfmGebXrfJDuoq9S9DH-SGsDYvmL_KMMu_KKFlU

{
    "title": "ChatGPT",
    "url": "http://google.com",
    "likes": 3
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NDM1MDYyMWExZGY4ZGM1YTQzM2JiZjYiLCJpYXQiOjE2ODEyMDQ2MjF9.hWCmmE0OG5S8FxxjxLCz19oZUozIzsS69YjrHiRdNvA

{
    "title": "Missing Like",
    "url": "http://google.com"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwiaWQiOiI2NDM1MDYyNGExZGY4ZGM1YTQzM2JiZmEiLCJpYXQiOjE2ODEyMDQ2NTd9.3UPWp-HcctjXM5tMQlY8xLh9nIxcyiyp1mvyrQTt1qc

{
    "title": "I'm a blog",
    "url": "http://google.com"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NDM1MDYyMWExZGY4ZGM1YTQzM2JiZjYiLCJpYXQiOjE2ODEzODA5ODh9.vYaSMyBhn1IHDJSV3CEfNxZUgemYMDyF7zmZnahlmjI

{
    "title": "I'm user test2",
    "author": "mr test2",
    "url": "http://google.com"
}
