PUT http://localhost:3003/api/blogs/6437aca9392b5d7ac5eadbc8 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NDM1MDYyMWExZGY4ZGM1YTQzM2JiZjYiLCJpYXQiOjE2ODEyMDQ2MjF9.hWCmmE0OG5S8FxxjxLCz19oZUozIzsS69YjrHiRdNvA

{
    "title": "Updated",
    "author": "Updated",
    "url": "http://google.com",
    "likes": 3
}